export {
    IconAngleRight,
    IconRubleSign,
    IconShekelSign,
    IconLariSign,
    IconYenSign,
    IconBahtSign,
    IconLiraSign,
    IconHryvniaSign,
    IconTengeSign,
    IconEuroSign,
    IconDollarSign,
    IconArrowLeftLong,
    IconXmark,
    IconCheck,
    IconBagShopping,
    IconPencil,
} from "@iconify-prerendered/vue-fa6-solid";
